<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <RootNamespace>TextChunkerConsole</RootNamespace>
    <AssemblyName>TextChunkerConsole</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TextChunker\TextChunker.csproj" />
  </ItemGroup>

</Project>
